# frozen_string_literal: true

require_relative "train/manifest"
require_relative "train/config"
require_relative "train/versions"
require_relative "train/notes"
require_relative "train/github"
require_relative "train/cut"
require_relative "train/hotfix"
require_relative "train/state_writer"
require_relative "train/append"
require_relative "train/config_edit"
require_relative "train/promote"
require_relative "train/merge"
require_relative "train/ai_notes"
require_relative "train/notes_lint"
